# Generated by Django 3.1.1 on 2020-09-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_t_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
