# Generated by Django 2.2.10 on 2021-08-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0003_t_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponser', models.CharField(max_length=80)),
                ('accountAddress', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
